# 1. Create a 1D NumPy array of numbers from 0 to 9.


In [1]:
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2. Create a 2x3 array of ones.


In [2]:
mat=np.ones((2,3))
mat

array([[1., 1., 1.],
       [1., 1., 1.]])

# 3. Create a 3x3 identity matrix.


In [3]:
mat=np.identity(3,dtype="int")
mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# 4. Create an array of 10 zeros.


In [4]:
a=np.zeros((5,2),dtype="int")
a

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

# 5. Create a 3x3 array of random integers between 1 and 10.


In [5]:
a=np.random.randint(0,10,(3,3))
a

array([[5, 9, 0],
       [7, 2, 2],
       [5, 8, 8]])

# 6. Reshape an array of 9 elements into a 3x3 matrix.


In [6]:
a=np.array([1,2,3,4,5,6,7,8,9])
mat=a.reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# 7. Find the sum of all elements in an array.


In [7]:
a=np.array([1,2,3,4,5,6,7,8,9])
sum=a.sum()
sum

45

# 8. Find the mean of an array.


In [8]:
a=np.array([1,2,3,4,5,6,7,8,9])
mean=a.mean()
mean

5.0

# 9. Find the median of an array.


In [9]:
a=np.array([1,2,3,4,5,6,7,8,9])
a.sort()
n=len(a)
mid=n//2
if n % 2 == 0:  
        median = (a[mid - 1] + a[mid]) / 2
else:  
        median = a[mid]
print(median)


5


# 10. Multiply all elements in an array by a scalar (e.g., 2).


In [10]:
a=np.array([1,2,3,4,5])
s=2
a=a*s
a

array([ 2,  4,  6,  8, 10])

# 11. Find the maximum and minimum values of an array.


In [11]:
a=np.array([1,2,3,4,5])
a_min=a.min()
a_max=a.max()
print(a_min,"\n", a_max)

1 
 5


# 12. Find the dot product of two arrays.


In [12]:
v1=np.array([1,2,3,4,5])
v2=np.array([1,2,3,4,5])
v1.dot(v2)

55

# 13. Find the index of the maximum value in an array.


In [13]:
a=np.array([1,2,3,4,5])
index_a_max=np.argmax(a)
index_a_max

4

# 14. Find the index of the minimum value in an array.


In [14]:
a=np.array([1,2,3,4,5])
index_a_min=np.argmin(a)
index_a_min

0

# 15. Sort an array in ascending order.


In [15]:
a=np.array([13,22,3,41,50])
sort_a=np.sort(a)
sort_a

array([ 3, 13, 22, 41, 50])